### ISSUE TITLE
How to connect 'User Subscription' Batch from Batch explorer

### ISSUE THREAD

**Issue by Gaploid** [Azure/azure-batch-samples#210] opened 2017-03-21 16:56 UTC
It seems 'User subscription' batch have the only way to connect through AAD https://blogs.technet.microsoft.com/windowshpc/2017/03/17/azure-batch-vnet-and-custom-image-support-for-virtual-machine-pools/ 

How can I do it with Batch Explorer?

**Comment by matthchr** [comment] 2017-03-21 17:50
Hi @Gaploid - Batch Explorer is intended as a sample and as such doesn't support every operation or experience which Azure Batch provides. We recommend if you're looking to monitor/manage your 'User subscription' account to use the Azure Portal or our new official tool [Batch Labs](https://github.com/Azure/BatchLabs), both of which do AAD auth and are also cross platform.

**Comment by Gaploid** [comment] 2017-03-21 18:20
@matthchr Wow, Thanks to point me on Batch labs. The azure portal is not friendly because you need contributor rights to view logs and etc. 

Can you share details on Batch labs? is it alpha/beta or already stable?

**Comment by matthchr** [comment] 2017-03-21 18:55
@paselem and @timotheeguerin are some of the main contributors to to Batch Labs , I'll let them answer on its level of stability.

The issue you mentioned about needing contributor rights to view logs - can you expand on that? With all AAD auth to the Batch Service you need at least read rights to the Batch Account I believe.

**Comment by paselem** [comment] 2017-03-21 20:46
@Gaploid - Batch Labs just got any real traffic this week and we are still in a 'Beta' stage. We'll be pushing out a stable branch in a few days. There isn't 100% feature parity with Batch Explorer, but if you find things that are hard or difficult to use I encourage you to raise issues so that we can address them.

I am also interested in the question posted by @matthchr regarding needing contributor rights to view logs. Which logs are you referring to? The portal should have no additional requirements to view task/node logs.

**Comment by Gaploid** [comment] 2017-03-21 20:50
Thanks guys. As I remember it was an error (crying cloud) without any additional info if we click on pools/jobs section in batch service page on Azure portal without contributor rights.

**Comment by paselem** [comment] 2017-03-21 20:53
@Gaploid - If you are able to reproduce that portal issue I would appreciate it so we can fix that as well. Enjoy using Batch Labs too and let us know if you have any feedback as we are quite actively working on it.

Thanks!
-Pablo

**Comment by matthchr** [comment] 2017-03-31 21:43
Closing this

**Closed by matthchr** 2017-03-31 21:43 UTC
